// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blueClosed': string;
  'blueOpened': string;
  'cell': string;
  'greenClosed': string;
  'greenOpened': string;
  'purpleClosed': string;
  'purpleOpened': string;
  'rainbow': string;
  'redClosed': string;
  'redOpened': string;
  'rotate': string;
  'text': string;
  'yellowClosed': string;
  'yellowOpened': string;
}
export const cssExports: CssExports;
export default cssExports;
