// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'closed': string;
  'opened': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
