// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'svgImage': string;
  'yearValue': string;
}
export const cssExports: CssExports;
export default cssExports;
